site_name: finance-agent
repo_url: https://github.com/Paraschamoli/finance-agent
site_url: https://Paraschamoli.github.io/finance-agent
site_description: This project builds an intelligent financial analysis agent that combines real-time market data and web search to generate structured, data-driven insights. It presents financial information in clear tables and concise summaries through an interactive playground interface, with flexible provider integration via OpenRouter.
site_author: Paras Chamoli
edit_uri: edit/main/docs/
repo_name: Paraschamoli/finance-agent
copyright: Maintained by <a href="https://Paraschamoli.com">Paraschamoli</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/finance_agent"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Paraschamoli/finance-agent
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/finance-agent

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
